### ISSUE TITLE
获取到的longitude是undefined 不知道是什么原因

### ISSUE THREAD

**Issue by idogoing** [kaixinhupo/cordova_location#2]
获取到的longitude是undefined 其余的参数都是正确的

**Comment by idogoing** [comment]
哥你把longitude 拼成了longtitude.....

**Comment by kaixinhupo** [comment]
枚举一下data看看都有哪些值，可能是拼写错误

在 2015-08-10 22:34:45，"idogoing" notifications@github.com 写道：

获取到的longitude是undefined 其余的参数都是正确的

**Comment by chenzbill** [comment]
把longtitude换成longitude就可以了,应该是拼错了....

**Comment by kaixinhupo** [comment]
@idogoing 
枚举一下data看看都有哪些值，可能是拼写错误

**Comment by kaixinhupo** [comment]
@chenzbill 
readme.md有一处拼写错误 我已经改正了
